/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalManagement;

import ui.AdministrativeRole.*;
import java.awt.CardLayout;
import javax.swing.*;
import ui.DonorManagement.DonorRegistrationWorkArea;
import ui.HospitalManagement.ViewHospitalJPanel;
import model.HospitalManagement.*;
import java.sql.*;
import model.users.User;

/**
 *
 * @author pranavb
 */
public class HospitalAdminRoleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminRoleJPanel
     */
    
    JPanel userProcessContainer = new JPanel();
    HospitalDirectory hospitalDirectory = new HospitalDirectory();
    DoctorDirectory doctorDirectory = new DoctorDirectory();
    Connection connection;
    Hospital hospital;
    public HospitalAdminRoleJPanel(JPanel userProcessContainer, HospitalDirectory hospitalDirectory, DoctorDirectory doctorDirectory, Connection connection, Hospital hospital, User user) {
        initComponents();
        String adminName = user.getUsername();
        lblAdminName.setText("WELCOME "+adminName);
        this.userProcessContainer = userProcessContainer;
        this.hospitalDirectory = hospitalDirectory;
        this.doctorDirectory = doctorDirectory;
        this.connection = connection;
        this.hospital = hospital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminName = new javax.swing.JLabel();
        btnCoordinatorManagement = new javax.swing.JButton();
        btnDoctorManagement = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 29, 29));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 830));
        setMinimumSize(new java.awt.Dimension(1200, 830));

        lblAdminName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCoordinatorManagement.setBackground(new java.awt.Color(111, 147, 146));
        btnCoordinatorManagement.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCoordinatorManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCoordinatorManagement.setText("MANAGE TRANSPLANT COORDINATORS");
        btnCoordinatorManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordinatorManagementActionPerformed(evt);
            }
        });

        btnDoctorManagement.setBackground(new java.awt.Color(111, 147, 146));
        btnDoctorManagement.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnDoctorManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctorManagement.setText("MANAGE DOCTORS");
        btnDoctorManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorManagementActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOSPITAL ADMINISTRATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDoctorManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(btnCoordinatorManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(384, 384, 384))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(394, 394, 394)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(374, 374, 374)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCoordinatorManagement, btnDoctorManagement});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAdminName)
                .addGap(148, 148, 148)
                .addComponent(btnDoctorManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCoordinatorManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(jLabel2)
                    .addContainerGap(748, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCoordinatorManagement, btnDoctorManagement});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorManagementActionPerformed
        // TODO add your handling code here:
        AddDoctorsJPanel addDoctorsJPanel = new AddDoctorsJPanel(this.userProcessContainer, this.hospitalDirectory, this.doctorDirectory , this.connection, this.hospital);
        userProcessContainer.add("AddDoctorsJPanel", addDoctorsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDoctorManagementActionPerformed

    private void btnCoordinatorManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordinatorManagementActionPerformed
        // TODO add your handling code here:
                
        DonorDetailJPanel donorDetailJPanel = new DonorDetailJPanel();
        userProcessContainer.add("DonorDetailJPanel", donorDetailJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCoordinatorManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoordinatorManagement;
    private javax.swing.JButton btnDoctorManagement;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAdminName;
    // End of variables declaration//GEN-END:variables
}
