/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdministrativeRole;
import DatabaseConn.DatabaseConnection;
import java.sql.*;
import model.donor.DonorRegistrationRequest;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import model.HospitalManagement.Hospital;
/**
 *
 * @author pranavb
 */
public class DonorRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorRequestJPanel
     */
    DatabaseConnection dbconnection = new DatabaseConnection();
    ArrayList<DonorRegistrationRequest> donorRequestDirectory = new ArrayList<DonorRegistrationRequest>();
    Connection connection;
    public DonorRequestJPanel() {
        initComponents();
        this.connection = dbconnection.getConnection();
        this.fetchDonorRequests();
        this.populateHospitalTable();
    }
    
    public void fetchDonorRequests() {
    String query = "SELECT RequestID, FirstName, MiddleName, LastName, DateOfBirth, " +
                   "AddressLine1, City, RequestDate FROM DonorRegistrationRequests";

    try {
        PreparedStatement stmt = this.connection.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();

        donorRequestDirectory.clear();

        while (rs.next()) {
            DonorRegistrationRequest request = new DonorRegistrationRequest();
            request.setFirstName(rs.getString("FirstName"));
            request.setMiddleName(rs.getString("MiddleName"));
            request.setLastName(rs.getString("LastName"));
            request.setDateOfBirth(rs.getString("DateOfBirth"));
            request.setAddress(rs.getString("AddressLine1"));
            request.setCity(rs.getString("City"));
            request.setRequestDate(rs.getString("RequestDate"));

            this.donorRequestDirectory.add(request);
        }

        rs.close();
        stmt.close();
    } catch (SQLException e) {
        e.printStackTrace();
        throw new RuntimeException("Error fetching donor registration requests: " + e.getMessage());
    }
}

    
     public void populateHospitalTable(){
                DefaultTableModel model = (DefaultTableModel) tblDonorRequests.getModel();
        
        model.setRowCount(0);
        
        for (DonorRegistrationRequest hospital  : this.donorRequestDirectory){
            Object[] row = new Object[5];
            row[0] = hospital;
            row[1] = hospital.getAddress();
            row[2] = hospital.getCity();

            
            model.addRow(row);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonorRequests = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1200, 830));
        setMinimumSize(new java.awt.Dimension(1200, 830));

        tblDonorRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Donor Name", "Donor Date of Birth", "Donor City"
            }
        ));
        jScrollPane1.setViewportView(tblDonorRequests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDonorRequests;
    // End of variables declaration//GEN-END:variables
}
